name: 'InfluxDB Action'
description: 'Install and configure InfluxDB and the InfluxDB CLI.'
branding:
  icon: 'database'
  color: 'gray-dark'
inputs:
  influxdb_version:
    description: 'Sets the version of InfluxDB to use (for example: 2.0.7). See https://portal.influxdata.com/downloads/ for versions. latest and nightly are also supported.'
    required: true
  influxdb_start:
    description: 'Set to false if you only need to use the cli tools without a locally running InfluxDB instance. If this is false, you can ignore the init parameters.'
    required: false
    default: 'true'
  influxdb_org:
    description: 'The initial Organization of the InfluxDB instance.'
    required: false
    default: 'organization'
  influxdb_user:
    description: 'The initial User of the InfluxDB instance.'
    required: false
    default: 'user'
  influxdb_password:
    description: 'The initial Password of the InfluxDB instance.'
    required: false
    default: 'password'
  influxdb_bucket:
    description: 'The initial Bucket of the InfluxDB instance.'
    required: false
    default: 'bucket'
  influxdb_token:
    description: 'The initial API Token of the InfluxDB instance.'
    required: false
runs:
  using: "composite"
  steps:
    - name: Download and Install InfluxDB
      run: |
        export INFLUXDB_VERSION=${{inputs.influxdb_version}}
        ${{ github.action_path }}/install-influxdb.sh
      shell: bash
    - name: Configure InfluxDB
      run: |
        export INFLUXDB_START=${{inputs.influxdb_start}}
        export INFLUXDB_ORG=${{inputs.influxdb_org}}
        export INFLUXDB_USER=${{inputs.influxdb_user}}
        export INFLUXDB_PASSWORD=${{inputs.influxdb_password}}
        export INFLUXDB_BUCKET=${{inputs.influxdb_bucket}}
        export INFLUXDB_TOKEN=${{inputs.influxdb_token}}
        ${{ github.action_path }}/setup-influxdb.sh
        unset INFLUXDB_PASSWORD
        unset INFLUXDB_TOKEN
      shell: bash
